### ISSUE TITLE
Why must system ops appear alone in a script?

### ISSUE THREAD

**Issue by infogulch** [cozodb/cozo#106]
Say I want to create a read-only relation with some fixed data, akin to an enum. I think it would be reasonable to expect that you can do this with one query, but instead it results in an error:

```
{
?[type] <- [['car'],['truck'],['van']]
:create vehicle_types{type}
}
{
::access_level read_only vehicle_types
}
```

Why must `::access_level` be executed in a separate query? Or `::relations` for that matter? Besides being an arbitrary restriction on how you organize your queries, it also prevents system ops from being used on *any* temporary/ephemeral relations, as they will be gone by the time the next query runs.

**Comment by zh217** [comment]
It's not arbitrary, as the single dot operations are used alongside a query, and the double dot operations are not. And in fact the system ops cannot be used with ephemeral relations (if you are thinking about indices), as the underlying storage is quite different.
