### ISSUE TITLE
Benchmarks don't build + Rustc version requirements 

### ISSUE THREAD

**Issue by Avi-D-coder** [cozodb/cozo#108]
Beyond just updating the benches this error brings up the question: what is the Rust version policy for this repo?
Should nightly be required for tests or benchmarks? Or should they be migrated to stable Rust?

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> cozo-core/benches/pokec.rs:8:12
  |
8 | #![feature(test)]
  |            ^^^^

error[E0063]: missing field `next` in initializer of `NamedRows`
   --> cozo-core/benches/pokec.rs:109:25
    |
109 |                         NamedRows {
    |                         ^^^^^^^^^ missing `next`

...
```

**Comment by zh217** [comment]
The missing field will be fixed. The benchmarks are at the moment not systematic and pretty outdated, and will be updated when time permits.
