### ISSUE TITLE
How to access generated default key

### ISSUE THREAD

**Issue by infogulch** [cozodb/cozo#109]
Say I have a `todo` relation, where I want to support changing the label/name of the todo later, and I want to allow users to have the same label twice. (I don't judge, list milk twice if you really don't want to forget it 😄.) Using an automatically generated uuid-based id field seems reasonable:

```
:create todo{id:Uuid default rand_uuid_v1() => label: String, done: Bool}
```

Then creating a new todo will automatically generate an id (nice!):

```
?[label,done] <- [['milk',false]]
:put todo{label,done}
```

But wait, after inserting the new todo for the user, I want to show it to them. How can I know what id was generated for this todo? The only valid way to query it is by id, but I have no way of knowing the id of the newly created row.

I think I want something like this, but I don't see how its possible:

```
{ ?[label,done] <- $input_data; :put todo{label,done} }
{ ?[id,label,done] := *todo{id,label,done}, id=<id_generated_in_previous_query> }
```

**Comment by zh217** [comment]
Yes it makes sense to have something like postgresql's `returning`. I will see how it can be implemented.

**Comment by zh217** [comment]
We will have something like this in the next release:

```
Welcome to the Cozo REPL.
Type a space followed by newline to enter multiline mode.
Loaded history from .cozo_repl_history
=> :create todo{id:Uuid default rand_uuid_v1() => label: String, done: Bool}

 status
--------
 "OK"
=> ?[label,done] <- [['milk',false]] :put todo{label,done} :returning
 _kind      | label                                           | done
------------+-------------------------------------------------+--------
 "inserted" | to_uuid("beecc992-f06d-11ed-8fd0-9cfe8cc4b38f") | "milk"
```

**Comment by infogulch** [comment]
I manually expanded the example and I guess the intention is for the output to look like this:

```
=> ?[label,done] <- [['milk',false], ['eggs', false]] :put todo{label,done => id} :returning
 _kind      | id                                               | label  | done
------------+--------------------------------------------------+--------+-------
 "inserted" | to_uuid("beecc992-f06d-11ed-8fd0-9cfe8cc4b38f")  | "milk" | false
 "inserted" | to_uuid("64434e42-f06f-11ed-a05b-0242ac120003 ") | "eggs" | false
```

You may see I also added an idea for how the user might indicate which fields they want, which borrows the [keys `=>` values](https://docs.cozodb.org/en/latest/stored.html#create-and-replace) syntax from the stored relations column spec. Except here, the variables listed on the left occur in the main rule, and the variables on the right are bound to other columns from the stored relation. I hope this inspires a suitable syntax. :)

**Comment by infogulch** [comment]
I expect I will often use this feature in combination with named return relations in chained queries [^1]. If that's true, then I might prefer not to have to type `:returning` on every query, and instead have it on by default.

[^1]: https://github.com/cozodb/cozo/issues/110

Notably this would affect the semantics of the last query in a query chain, but not any of the prior queries since currently they can't reference each other anyway. However, if the last or only query is a mutation then the cozo library api semantics will change from returning a status field to returning a full result set, which may cause issues in user code or language binding libraries.

Users can mitigate the change in semantics by adding a status query at the end like `{:put} {?[status] <- [['OK']]}`, or you could add a new silencing command like `:quiet`.

I am not in a position to measure the impact of this change or judge the benefit to breakage ratio.

**Comment by zh217** [comment]
I don't think we want to have it on by default, as

- It has performance penalties, sometimes significant
- `:returning` really isn't too much to type
- We don't want what is not in the query to change the semantics (no hidden options)

**Comment by zh217** [comment]
`:returning` is available now, so closing this.
