### ISSUE TITLE
Conda packages?

### ISSUE THREAD

**Issue by makkus** [cozodb/cozo#11]
Hi there, brilliant project, thanks a lot! Are there any plans to build and provide conda packages for cozo? I have never packaged a Python package that wraps Rust code, so no idea if it's easily doable and I can just do it myself, or whether it requires an involved build setup...

**Comment by zh217** [comment]
I'm not familiar with packaging for conda either. Are there any specific reason that you must use a conda package instead of the existing pypi package? As you can use pypi packages inside conda environments just fine, I don't really see the benefits.

**Comment by makkus** [comment]
The main reason is that it streamlines the install of my package if conda is used (which it is for my project as it simplifies a few things with native dependencies). As far as I'm aware, I can only add conda dependencies to the (conda) package description of my own package. If one of the dependencies is not available in conda, either users would have to manually install it via pip, or I would have to wrap the whole install process into a script that executes two steps (first create conda env and install conda dependencies, then do the pip stuff). 
This creates additional friction and makes the process more fragile. It's not an issue when setting up a dev environment etc., but for shipping end-user applications i've come to appreciate the simplicity. 

I can appreciate this not being anywhere near your list of priorities, just wondering whether there are any plans from your side. And it's not an issue for me until cozo is recommended for production use anyway. I might try to figure out packaging Rust code in conda myself if I find a spare minute, and I can publish cozo on my own conda channel, and I can share the CI setup with anyone who is interested.

**Comment by zh217** [comment]
Thanks for your understanding. Our priority is indeed improving the core library at the moment. If you want to investigate how to package cozo for conda, the [cozo-lib-python](https://github.com/cozodb/cozo-lib-python) package that provides the nativing binding is built with [maturin](https://www.maturin.rs/). I'm not sure if maturin plays well with conda. If maturin proves to be trouble, you might be better off wrapping the [C library](https://github.com/cozodb/cozo/tree/main/cozo-lib-c) instead.

**Comment by makkus** [comment]
Thanks, will have a look!
