### ISSUE TITLE
Can a chained query access a preceding query's return relation?

### ISSUE THREAD

**Issue by infogulch** [cozodb/cozo#110]
Is there some way for [chained queries](https://docs.cozodb.org/en/latest/stored.html#chaining-queries) to access the [return relation](https://docs.cozodb.org/en/latest/tutorial.html#Rules-and-relations) of a preceding query?

As in:

```
{
?[a,b] <- [[1,'a'],[2,'b'],[3,'a']]
}
{
?[sum(a),count_unique(b)] := _symbol_that_refers_to_previous_query{a,b}
# returns [6,2]
}
```

Or to borrow from sql:

```
{
?[a,b] <- [[1,'a'],[2,'b']]
} as my_return_relation
{
?[sum(a),count_unique(b)] := my_return_relation{a,b}
}
```

**Comment by zh217** [comment]
There was something like this in CozoDB, but was removed since with branching and recursion it becomes pretty confusing what is "previous", and led to a quite a few subtle bugs in applications. Please use ephemeral relations for this. If getting autogenerated ID is an issue, I think in this this is a case where manually generating ID with functions and storing them in another ephemeral relation is justified.

**Comment by infogulch** [comment]
> with branching and recursion it becomes pretty confusing what is "previous"

This seems to conflict with the docs on chained queries:

> Execution proceeds for each query *serially*, and aborts at the first error encountered.

I don't see how users can access recursive semantics when each query is required to terminate and succeed before the next query is invoked.

The way I'm imagining it is that a previous chained query's returned relations can be used as if it were a read-only ephemeral relation.

**Comment by zh217** [comment]
It's completely deterministic but confusing. For example:

```
{ query A }
%if { query B }
%then { query C}
...
```

So with respect to query C, which query do you think generates the "previous return?" The answer is that of query B. It gets even weirder with loops and nested branches: in loops the last query of the previous iteration is the "previous return", except the first iteration. Even if you are beginning with a linear chain of queries, you can't be sure that someone will not come and add some stuff in later. Then it might work fine for most cases, except a few corner ones. The "previous return" stuff is basically a minefield. In programming languages, REPLs sometimes have it as a convenience for quick and dirty stuff, and that's about it. It is just too dangerous to use for permanent serious stuff.

**Comment by infogulch** [comment]
> The "previous return" stuff is basically a minefield.

Oh I see, that's a problem I did not consider. I agree that when considering the `%if` etc meta language of chained queries then the concept  of 'the previous query' is fuzzy enough to cause confusion.

But what if we pivot a bit and follow SQL's path of *naming* previous returned relations?

```
{ query A } as my_a
%if { query B } as my_b
%then { query C }
```

Here if query C uses `my_a` or `my_b` then there is no ambiguity. Same with someone adding new query in between two others in a long chain, since all references are named then it doesn't introduce any extra confusion. As for loops and nested branches the right approach may be to limit references to strictly preceding returned relations: disallow references to queries in the previous loop iteration or outside the current branch path.

**Comment by zh217** [comment]
I think the `as` syntax looks clean and provides a way to reduce boilerplate. It is not as powerful as the full syntax as it cannot specify types or non-key columns, and would only be suitable for making immutable relations. I will see how best to incorporate it (I think it would be pretty easy).

**Comment by zh217** [comment]
the `{} as _rel` syntax is supported now, so closing this.
