### ISSUE TITLE
The CLA action seems to run on every comment.

### ISSUE THREAD

**Issue by Avi-D-coder** [cozodb/cozo#112]
Commenting on issues triggers, the CLA github action.

**Comment by Avi-D-coder** [comment]
test

**Comment by Avi-D-coder** [comment]
https://github.com/cozodb/cozo/actions/runs/4963191669

**Comment by zh217** [comment]
This looks harmless to me, does it cause any problems?

**Comment by Avi-D-coder** [comment]
No real issues just extra notifications

**Comment by infogulch** [comment]
Should be configurable, no?

https://github.com/settings/notifications

> System > Actions > Notifications for workflow runs on repositories set up with GitHub Actions
