### ISSUE TITLE
unexpected error of function `trim_start`

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#113]
Hi,

Consider the following program:

```
itwn[] <- [["a", 1]]

bzwp[B] := itwn[B, A], str_includes(trim_start(B), "a")
atwm[B] := bzwp[B]
vdbx[A] := itwn[C, A]
qzjb[I, F] := atwm[F], itwn[F, I]
aqms[A, A] := vdbx[B], qzjb[A, B]
?[A, B] := aqms[A, B]
```
This program triggers an error in https://www.cozodb.org/wasm-demo/ 
```
eval::throw

  × Evaluation of expression failed
   ╭─[2:1]
 2 │ 
 3 │ bzwp[B] := itwn[B, A], str_includes(trim_start(B), "a")
   ·                                     ─────────────
 4 │ atwm[B] := bzwp[B]
   ╰────
  help: 'trim_start' requires strings
```
But the input of `trim_start` is `B`, which is the first variable of `itwn`, I think it is a string.
If I query `bzwp` like `?[A] := bzwp[A]`, then I will not meet this error.

I guess the reason is that in rule `aqms[A, A] := vdbx[B], qzjb[A, B]`, I compare an integer with a string.

But the following program can not trigger this error:
```
a[] <- [[1]]
b[] <- [["a"]]
c[A] := b[A], str_includes(trim_start(A), "a")
?[A] := a[A], c[A]
```

**Comment by zh217** [comment]
This is because magic set rewrite has problems when dealing with repeated variables in the head. It will be fixed.

**Comment by DerZc** [comment]
I got it! Thank you for your explanation!

**Comment by zh217** [comment]
Another reason that we don't want to turn off this optimization can also be seen from the program. Imagine that in

```
itwn[A] <- [["a"]]
bzwp[A] := itwn[A], str_includes(trim_start(A), "a")
?[A] := bzwp[1], A = 1
```
the `itwn` relation, instead of containing a single row, contains a trillion rows instead. With the optimization we save a lot of useless computation.

**Comment by DerZc** [comment]
Hi @zh217 I agree with you! Thanks a lot for your detailed explanation!
