### ISSUE TITLE
Odd index creation parsing

### ISSUE THREAD

**Issue by Avi-D-coder** [cozodb/cozo#115]
Attempting to create an index in the same script as table creation results in a parse error.
It has to be done separately in two scripts. How do you do it in one script.

```
:create rel {a => b}
```

```
::index create r:idx {b, a}
```

None of these work

```
{:create r {a => b}}
{::index create r:idx {b, a}}
```

```
:create rel {a => b}
::index create r:idx {b, a}
```

```
{:create r {a => b}}
::index create r:idx {b, a}
```

```
  × The query parser has encountered unexpected input / end of input at 21..21
   ╭─[1:1]
 1 │ {:create r {a => b}}
 2 │ ::index create r:idx {b, a}
   · ▲
   ╰────
```

**Comment by infogulch** [comment]
I agree it would be nice to be able to create a complete schema with one script. See also #106.

**Comment by zh217** [comment]
It must be done separately now. Indices creation involves more work to do than simple relations. Work is ongoing to remove this restriction.

**Comment by andrewbaxter** [comment]
AFAICT this should be in 0.7.6 but I'm still hitting the same error.  There's no note on https://docs.cozodb.org/en/latest/stored.html#indices about needing to run these as a separate query, and per the above comment ("System ops in script has been implemented") it sounds like this should no longer be a restriction.

```
{:create x {a: Int, => b: Int}}
::index create x:r {b, a}
```
```
  × The query parser has encountered unexpected input / end of input at 32..32
   ╭─[1:1]
 1 │ {:create x {a: Int, => b: Int}}
 2 │ ::index create x:r {b, a} 
   · ▲
   ╰────
```

The system ops page says `must appear alone in a script`, so I'm not sure.
