### ISSUE TITLE
Document storage strategies/architecture 

### ISSUE THREAD

**Issue by vlmutolo** [cozodb/cozo#12]
I hunted around for this information briefly but couldn't find it. How are data and relations stored in cozo? 

The primary thing I'm wondering is if Cozo is row-oriented or column-oriented. General-purpose databases have traditionally all stored rows contiguously, but storing similar data types continuously opens up big opportunities for compression and analytics workflows.

**Comment by zh217** [comment]
It's row-oriented. You are absolutely right that this should be documented. Will keep this issue open until it is done.

We are also in the process of separating the internal storage API. When that is done, we will be able to easily use storage engines other than RocksDB. We might also see what we can do about optional columnar data support.

**Comment by zh217** [comment]
The new README https://github.com/cozodb/cozo/commit/2c872e6982a652ea194a1b68c3c95629b44daa6e now contains a section about this information.
