### ISSUE TITLE
Unexpected result of `ge` on `-0.0` and `0.0` under magic rewrite

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#122]
Hi,

Consider the following program:
```
phve[a, b] <- [[-0.0, null], [0.0, null]]
xukw[A, B] := phve[A, B], ge(A, 0)
nwku[F] := phve[_, F]

ssie[C, F] := nwku[C], xukw[F, C]
?[a, b] := ssie[a, b]
```
I get the results `[[null, -0.0], [null, 0.0]]`, but the value of `nwku` is `[[null]]` and the value of `xukw` is `[[0.0, null]]`, so the result of `ssie` should not be `[null, -0.0]`.

I also tried to add `:disable_magic_rewrite true`, then I got correct results.

I can reproduce this on version `0.7.1`

**Comment by zh217** [comment]
Interesting, seems that this only happens with -0.0 and not with any other number.

**Comment by zh217** [comment]
The gist of the problem can be summarized in:

```
?[] <- [[0.0 >= 0, -0.0 >= 0, -0.0 >= 0.0, 0.0 >= -0.0]]
```
It looks like the second one shouldn't be true, but actually, for python, it is:
```
>>> 0.0 >= 0
True
>>> -0.0 >= 0
True
>>> -0.0 >= 0.0
True
>>> 0.0 >= -0.0
True
```
Not sure what can be done. Going the python way basically means that we will eliminate -0.0 from numbers, and I'm not sure that's what we want to do. Making the second one `false` as well means that we could mess up with the memcomparable format. Floating point numbers are hard.

**Comment by zh217** [comment]
It seems Rust agrees with python:
```
assert!(0.0 >= -0.0);
assert!(-0.0 >= 0.0);
```
passes.

**Comment by DerZc** [comment]
Hi @zh217 I have a small question. For this test case, is this problem caused by the transformation of `ge(A, 0)` to `ge(A, 0.0)` under the magic rewrite?

**Comment by zh217** [comment]
No, magic rewrite doesn't change that. It is caused by magic rewrite enables the range scan on the relation `phve` instead of testing every value.

**Comment by DerZc** [comment]
I got it! Thank you very much!

**Comment by DerZc** [comment]
I'm very sorry to disturb you. But I have another question. When does the magic set rewrite get triggered?
The following program should be equivalent to the this test case:
```
phve[a, b] <- [[-0.0, null], [0.0, null]]
xukw[A, B] := phve[A, B], ge(A, 0)
ssie[C, F] := phve[_, C], xukw[F, C]
?[a, b] := ssie[a, b]
```
But this program produces correct results, which means it not triggers range scan.

(By the way, there is a small error in the document of magic set rewrite https://docs.cozodb.org/en/latest/execution.html#magic-set-rewrites, the first line of the example should be `reachable[a, b] := link[a, b]`, otherwise, `b` is unbound.)

**Comment by DerZc** [comment]
Hi @zh217 so sorry to disturb you. Do you have documents available that outlines the specific case under which the magic set rewrite is applied? I just have the questions mentioned above.

**Comment by DerZc** [comment]
I got it! Thank you very much for taking the time to respond to me amid your busy schedule!
