### ISSUE TITLE
SSE APIs documentation

### ISSUE THREAD

**Issue by comunidadio** [cozodb/cozo#126]
Namely:
GET(SSE) /changes/{relation: String}
GET(SSE) /rules/{name: String}

First, I'd like to say those APIs are truly brilliant, enabling so many possibilities.
SSE is such a overlooked and clean web API, perfect match for this.

I tried the /changes API, cozo seems to register the SSE handler fine, but I'm unable to get any modification event despite successful writes to the relation:

Tried both /changes/route and /changes/*route (using the demo airport "route" relation):

[2023-05-25T04:21:24Z INFO  cozo_bin::server] starting changes SSE route: 0
[2023-05-25T04:21:24Z INFO  cozo_bin::server] starting changes SSE *route: 1

Registering SSE like this:
var source = new EventSource("http://localhost:9070/changes/route");
source.onmessage = (event) => console.log("EVENT", event)

Then writing to the relation like this:
await run("?[fr,to,dist] <- [['AIRPORT1','AIRPORT2', 13000]]   :put route {fr,to,dist}")

The write is OK, but not getting any SSE event back.

Am I missing registering the SSE the wrong way?

---

Also for the /rules SSE, is it OK to register multiple times for the same rule name? As in, each 'registration' would be counted as a potential separate thread for the computation? (if the query permits of course)

**Comment by zh217** [comment]
For `/changes/rel`, you can test with curl: `curl -N localhost:9070/changes/rel` and see if it registers any events.

If `curl` works but nodejs does not, then mostly likely the javascript library is sending headers to the server stating that it is OK with compressed data (like gzip), but when the compressed data actually comes it fails to decode it. We have seen it in python. It seems that most SSE servers do not send compressed data even when asked (but ours do).

For `/rules`, it is not OK to register for multiple times for the same rule name. Also `/rules` API may change in the next version.

**Comment by zh217** [comment]
That's indeed interesting. I will dig deeper to see how to make it browser-compatible out-of-box.
