### ISSUE TITLE
How to optimize the speed of hnsw vector index creation?

### ISSUE THREAD

**Issue by yandili** [cozodb/cozo#128]
This project is great and it's very convenient to write with datalog!

I tried the hnsw vector search feature but found it to be quite slow to build the index. My vector has a dimension of `(50000,48)`, and is made up of floating point numbers. The parameters used to build the index were `m=32, L2, and ef_construction=20`. This process took nearly 5 minutes, while the same vector indexed in Milvus (alternative to faiss, PQ-index) only took <10 seconds. I'm not sure if this is a configuration issue or if the performance can be improved. The curret time is a bit long.

```python
from pycozo.client import Client
client = Client('rocksdb', 'uncommitted/vec.spr.db')

# create embedding space
dim = 48
client.run(f"""
  :create embedding {{
    pt: String,
    id: Int
    =>
    embedding: <F32; {dim}>
  }}
""")

# insert embedding, pretty fast
for pt in tokenizer:
  vectors = open(os.path.join(tboard_embedding_path, pt, "tensors.tsv")).readlines()
  vectors = [list(map(float, v.rstrip("\r\n").split("\t"))) for v in vectors]
  vectors = sphereize_data(np.array(vectors)).tolist()
  vectors = [
    {"pt": pt, "id": i, "embedding": v} for i, v in enumerate(vectors)
  ]
  client.put("embedding", vectors)


# create hnsw index for embedding
# this takes roughly 5min
client.run(f"""
  ::hnsw create embedding:index {{
    dim: {dim},
    m: 32, 
    dtype: F32,
    distance: L2,
    fields: [embedding],
    ef_construction: 20
  }}
""")
```

**Comment by zh217** [comment]
It shouldn't be this slow. I will look into it. Thanks for the report.
