### ISSUE TITLE
Bulk ingestion

### ISSUE THREAD

**Issue by maxott** [cozodb/cozo#13]
Hi, I'm very excited seeing this project as it seem to fit perfectly what I need very soon.

My initial question would be concerning efficient ingestion of base facts. My current use case is provenance tracking combined with analytics results in distributed environments, so there'll potentially be lots of largish chunks of records. Right now the only API I can see is building a "query' string with a list of parameters. Is there a different option? 

It's not a showstopper for me right now, but would be nice knowing on what your current thinking regarding a roadmap is. 

Thanks

**Comment by maxott** [comment]
Oh, I just went back to the manual and saw `CsvReader` and `JsonReader` in the utilities section. I would prefer to run the standalone server. For someone who has never programmed in Rust, how difficult would it be to add a POST target to the existing server which would use those utilities (which currently are expected to pull data).

**Comment by zh217** [comment]
Thanks for your interest! Good idea about POSTing to API to ingest data. It's not hard just some routine work. Will keep this issue open until it is implemented.

**Comment by maxott** [comment]
Thanks. On that topic, I'm still unclear when "things" will be persisted and when will they just stay in memory.

**Comment by zh217** [comment]
Queries execute synchronously from the perspective of the user. In other words, stored relations are persisted as soon as the query executes successfully.

**Comment by maxott** [comment]
Thanks, I'm starting to get the hang of it.
