### ISSUE TITLE
Cannot drop FTS index, it says it can't find it

### ISSUE THREAD

**Issue by Madd0g** [cozodb/cozo#143]
I'm using cozo-node.

I have this block:

```
#::fts drop entity:fts_index
::fts create entity:fts_index {
	extractor: name,
	#extract_filter: !is_null(name),
	tokenizer: Simple,
	filters: [Lowercase],
}
```

I could only create the index once, I realized I wanted the lowercase filter later, but when I try to drop the index, I get `index fts_index for relation entity not found`, but when I try to create it, it says that it already exists

**Comment by zh217** [comment]
Confirmed -- thanks for the report!
