### ISSUE TITLE
Usage of functions is not clear

### ISSUE THREAD

**Issue by mtnygard** [cozodb/cozo#17]
The [list functions](https://cozodb.github.io/current/manual/functions.html#list-functions) are documented, but it is not clear from the manual or the tutorial how to apply them.

For example, with the `list` function... other than calling `list(1, 2, 3)` in the right-hand side of a rule, how would it be used?

It doesn't seem to work as an aggregator.

**Comment by zh217** [comment]
Functions and aggregators are separate things. The aggregator you are looking for is [collect](https://cozodb.github.io/current/manual/aggregations.html#Aggr.Ord.collect).
