### ISSUE TITLE
Extend CozoScript with ` allbut ` and ` select * ` projection operators

### ISSUE THREAD

**Issue by athanhat** [cozodb/cozo#172]
Hi, I think CozoScript can become a lot more user friendly if you can add these projection operators

1. [allbut](https://www.try-alf.org/doc/api/allbut)
Description: Computes the relation obtained by removing a subset of attributes from operand tuples.
This operator is the inverse of project. While the latter keeps attributes, this one removes them.

2. [select * from Rel or select Rel.*](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-select/)
Description:  If you want to select data from all the columns of the table, you can use an asterisk (*) shorthand instead of specifying all the column names.

I have studied CozoDB documentation and I played with the tutorial example. I could not find anything that matches (select * from Rel), neither there is an `allbut` operator for projection. Is there any quick way to implement these or use them with any specific expressions/predicates in the current version of CozoScript ? 

Do I miss something here, please let me know
Thanks

**Comment by srnnkls** [comment]
Why is this closed? Can you reopen @athanhat?
