### ISSUE TITLE
Problem with Rust regular expressions in CozoScript Regex functions

### ISSUE THREAD

**Issue by athanhat** [cozodb/cozo#173]
Hi, here is a simple graph database and the query to demonstrate the problem I have

In fact, your followers will find interesting KGTK tool and Kypher language. I am converting their [introductory tutorial](https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/01-kgtk-introduction.ipynb) to CozoDB because it is easier to do modeling and queries using a relational database rather than working with triplets and query languages like SPARQL and Cypher that are based on them. 

```python
%set smallgraph "file://small-graph.csv"

{:create SG {id: String =>  node1: String, label:String, node2:String}}
SGraph[] <~ CsvReader(types: ['String', 'String', 'String', 'String'], 
                      url: $smallgraph, 
                      delimiter: '\t', 
                      has_headers: true)

?[id, node1, label, node2] := SGraph[id, node1, label, node2]
:put SG {id => node1, label, node2}

?[id, node1, label, node2] := *SG[id, node1, label, node2]

 id   | node1              | label       | node2 
------+--------------------+-------------+------------------------------
 "e1" | "m_shriver"        | "spouse"    | "a_schwarzenegger" 
 "e2" | "a_schwarzenegger" | "coactor"   | "l_hamilton" 
 "e3" | "g_rydstrom"       | "colleague" | "g_borders" 
 "e4" | "g_rydstrom"       | "colleague" | "a_schwarzenegger" 
 "e5" | "a_schwarzenegger" | "name"      | "'Arnold Schwarzenegger'@de" 
 "e6" | "l_hamilton"       | "name"      | "'Linda Hamilton'@en" 
 "e7" | "g_rydstrom"       | "name"      | "'Gary R. Rydstrom'@en" 
 "e8" | "g_borders"        | "name"      | "'Gloria S. Borders'@en" 
 "e9" | "m_shriver"        | "name"      | "'Maria Shriver'@en" 
```
Here is the data file
[small-graph.csv](https://github.com/cozodb/cozo/files/12467049/small-graph.csv)

OK I tried the following regular expressions in CozoScript 
```bash
cozo --version
cozo-bin 0.7.2 (cozo-0.7.2-x86_64-unknown-linux-musl)
```
and in Kypher

1. Match names (values-objects in node2) that contain a double letter
    Rust regular expression: `.*(.)\\1.*` or `.*([a-zA-Z])\\1.*`
    
### CozoScript Query
```python
?[id, node1, label, node2] := *SG{id, node1, label, node2}, 
                              label=='name', 
                              regex_matches(node2, ".*(.)\\1.*")

 id | node1 | label | node2 
----+-------+-------+-------
```
It should match and return
```python
id   | node1              | label  | node2 
------+--------------------+--------+------------------------------
 "e5" | "a_schwarzenegger" | "name" | "'Arnold Schwarzenegger'@de"
```
2. Match any name that contains a capital letter followed by a period.
    Rust regular expression: `.*[A-Z]\\..*`

It should match and return, I used a string function here to get the result,
```python
?[id, node1, label, node2] := *SG{id, node1, label, node2}, 
                              label=='name', 
                              str_includes(node2, ".") 

 id   | node1        | label  | node2 
------+--------------+--------+--------------------------
 "e7" | "g_rydstrom" | "name" | "'Gary R. Rydstrom'@en" 
 "e8" | "g_borders"  | "name" | "'Gloria S. Borders'@en" 
```
3. Extract the year from a string that has this format "^1991-07-03T00:00:00Z/11"
    I tried with `year=regex_extract_first(node2, "^\d{4}")`

That is all, please let me know if that is a bug or I have a syntax, typing error in my regular expressions
Thank you

PS: In Kypher (KGTK) by default * is used which means all columns of matching edge(s) are output
Generally speaking I am missing a lot projection of all columns (attributes)  of Relation, i.e. select * 
I have raised an issue  [#172], it would be great if you can add this feature in an incoming release of CozoScript. Is there an alternative that escaped my attention ?

**Comment by athanhat** [comment]
OK I got it, it's a syntax problem I have. Here are the regular expressions that work with CozoScript
1. Match names (values-objects in node2) that contain a double letter


3. Extract the year from a string that has this format "^1991-07-03T00:00:00Z/11"
```python
year=regex_extract_first(node2, "\d{4}"
```

**Comment by infogulch** [comment]
So rust regex is limited in that it doesn't support backreferences in order to [avoid worst-case performance scenarios](https://docs.rs/regex/latest/regex/), and backreferences is the feature you need to search for this double-letter pattern generically. [See SO answer](https://stackoverflow.com/a/71997126/213246).

If you only care about ascii results, the best workaround is probably just listing them out: `"aa|bb|cc|dd|ee|..."`, which may be dissatisfying at first but will work great and lets you move on to the next important problem.
