### ISSUE TITLE
Alternative storage engine, in memory data structure for CozoDB

### ISSUE THREAD

**Issue by athanhat** [cozodb/cozo#175]
Hi, I have something better to propose as an alternative storage engine and/or in-memory data structure for processing for CozoDB. I am also trying to understand any technical issues that prevents you from integrating these in your project.

> The RocksDB engine is crazy fast for both reads and writes and can handle an enormous amount of concurrency, while still being rather conservative on resource usage. In particular, its storage on disk is compressed, making its disk space requirements for live databases the smallest among all persistent options. 
Source: [Cozo runs (almost) everywhere](https://docs.cozodb.org/en/latest/releases/v0.2.html#cozo-runs-almost-everywhere)

Well, if you think RocksDB is crazy fast for both reads and writes please consider the following benchmark I ran on this dataset  [tsv file](https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/datasets/arnold-profiled/all.tsv.gz). It is the same dataset I used in #174.

### Clickhouse and Polars
Both are strongly based on vectorized parallel execution. The first excels as a columnar database with its excellent Merge Tree engine, a different but a lot faster engine than the LSM tree (RocksDB). The second, written in Rust, is among the fastest for in-memory dataframe  processing.

#### Import data
| DBMS | Time |
| --- | --- |
| Polars | 0.308 sec |
| Clickhouse | 2.3 sec |
| CozoDB In-Mem |  16.4 sec |
| CozoDB + RocksDB | 29.6 sec |

```sql
CREATE TABLE akb
(
`from` String default '<NI>',
`via` String default '<NI>',
`to` String default '<NI>',
`rid` String,
`totype` String default '<NI>',
)
ENGINE = MergeTree()
ORDER BY (from, via, to)
```

```bash
time clickhouse-client --query="INSERT INTO akb FORMAT TabSeparated" < all.tsv
```

#### Table size on disk

| Database | Size |
| --- | --- |
|Clickhouse | 91.23 MB |
| CozoDB + RocksDB | 165.05 MB |

```sql
SELECT table, formatReadableSize(sum(bytes)) AS size
FROM system.parts
WHERE active AND (table = 'akb')
GROUP BY table
```

#### Count total number of rows
| DBMS | Time |
| --- | --- |
| Polars | 0.000304 sec (304 μs)|
| Clickhouse | 0.002 sec |
| wc -l | 0.097 sec |
| CozoDB In Memory | 1.450 sec |
| CozoDB + RocksDB | 2.730 sec |

```sql
SELECT count(*) as nrows FROM akb

# nrows: 3680804
# 1 row in set. Elapsed: 0.002 sec. (2msec) !!!

# time wc -l all.tsv
# 3680804 all.tsv
# real   0.097 sec

# Wall time: RocksDB
# nrows: 3603898
# 3.11 sec
```

#### Arnold aliases

| DBMS | Time |
| --- | --- |
| Polars | 0.009 sec |
| Clickhouse | 0.009 sec |
| CozoDB In Mem | 1.290 sec |
| CozoDB + RocksDB | 2.540 sec |

```sql
SELECT from, via, to, totype
FROM akb
WHERE (from = 'Q2685') AND (via = 'alias')

┌─from──┬─via───┬─to───────────────────────────────┬─totype─┐
│ Q2685 │ alias │ 'Arnie'@en                       │        │
│ Q2685 │ alias │ 'Arnold Alois Schwarzenegger'@en │        │
│ Q2685 │ alias │ 'Arnold Strong'@en               │        │
│ Q2685 │ alias │ 'Governator'@en                  │        │
│ Q2685 │ alias │ 'Governor Schwarzenegger'@en     │        │
│ Q2685 │ alias │ 'Schwarzenegger'@en              │        │
│ Q2685 │ alias │ 'The Styrian Oak'@en             │        │
│ Q2685 │ alias │ 'The Terminator'@en              │        │
└───────┴───────┴──────────────────────────────────┴────────┘

8 rows in set. Elapsed: 0.009 sec. Processed 32.37 thousand rows, 1.16 MB (3.69 million rows/s., 132.32 MB/s.)

?[from, via, to, totype] := *AG{from, via, to, totype}, from="Q2685", via="alias"
```

#### Arnold children
Here is another query to fetch Arnold children with their aliases. 
There is a significant contrast in performance by several orders of magnitude, same like the previous query:

| DBMS | Time |
| --- | --- |
| Clickhouse | 0.022 sec |
| Polars | 0.027 sec |
| CozoDB In Mem | 2.100 sec |
| CozoDB + RocksDB | 4.230 sec |

```sql
Children[from, via, to] := *AG[_, "Q2685", via, to, totype], 
                           from="arnold", via="P40", totype="wikibase-item"
?[who, child, name] := Children[who, via, child], *AG{from: child, via: "alias", to: name}

# RocksDB Wall time: 16.8 s

select 'arnold' as who, child, name 
from (select from as child, to as name  
         from akb 
         where from in (select to from akb where from='Q2685' and via='P40') and via='alias')

┌─who────┬─child─────┬─name────────────────────────────────────────┐
│ arnold │ Q28109921 │ 'Christina Aurelia Shwarzenagger'@en        │
│ arnold │ Q28109921 │ 'Christina Maria Aurelia Schwarzenegger'@en │
│ arnold │ Q28109921 │ 'Schwarzenegger, Christina'@en              │
│ arnold │ Q28109928 │ 'Christopher Sargent Schwarzenegger'@en     │
│ arnold │ Q28109928 │ 'Schwarzenegger, Christopher'@en            │
│ arnold │ Q4521676  │ 'Katherine Eunice Schwarzenegger'@en        │
│ arnold │ Q4521676  │ 'Schwarzenegger, Katherine'@en              │
│ arnold │ Q901541   │ 'Patrick Arnold Shriver Schwarzenegger'@en  │
│ arnold │ Q901541   │ 'Patrick Shriver'@en                        │
│ arnold │ Q901541   │ 'Patrick Shwarzenagger'@en                  │
└────────┴───────────┴─────────────────────────────────────────────┘

10 rows in set. Elapsed: 0.022 sec. 
Processed 106.10 thousand rows, 2.91 MB (5.51 million rows/s., 151.38 MB/s.)
```

#### Point query
ClickHouse is blazing fast even for point queries, despite the fact it scans all the rows in the table. Polars is lightning fast for this specific kind of queries.

The following query retrieves a specific row from the table based on the unique identifier (rid)

| DBMS | Time |
| --- | --- |
| Polars | 0.011 sec |
| Clickhouse | 0.040 sec |
| CozoDB In Mem | 1.410 sec |
| CozoDB + RocksDB | 2.610 sec |

```sql
SELECT * FROM akb
WHERE rid = 'Q4521676-alias-en-adfdbd-0'

┌─from─────┬─via───┬─to───────────────────────────────────┬─rid────────────────────────┬─totype─┐
│ Q4521676 │ alias │ 'Katherine Eunice Schwarzenegger'@en │ Q4521676-alias-en-adfdbd-0 │        │
└──────────┴───────┴──────────────────────────────────────┴────────────────────────────┴────────┘

1 row in set. Elapsed: 0.040 sec. 
Processed 3.68 million rows, 154.82 MB (92.12 million rows/s., 3.87 GB/s.)
```

### Question1: Is it possible to use ClickHouse as a backend ?

This reference in documentation looks promising: 

> If you are using the database embedded in Rust, you can even provide your own custom backend. The storage engine also defines a _row-oriented_ binary data format, which the storage engine implementation does not need to know anything about. This format contains an implementation of the [memcomparable format](https://github.com/facebook/mysql-5.6/wiki/MyRocks-record-format#memcomparable-format) used for the keys, which enables the storage of rows of data as binary blobs that, when sorted lexicographically, give the correct order
Source: [README.md](https://github.com/cozodb/cozo#query-engine)

I had a quick look at the source code, Cozo [creates a table with a primary key and a value of type BLOB in SQLite](https://github.com/cozodb/cozo/blob/febf96e4b99fb9d2f579f20780a551c385c372a9/cozo-core/src/storage/sqlite.rs#L43)

CilickHouse can store strings of an arbitrary length. The length is not limited. The value can contain an arbitrary set of bytes, including null bytes. The String type [replaces the types VARCHAR, BLOB, CLOB, and others from other DBMSs](https://clickhouse.com/docs/en/sql-reference/data-types/string).
But be aware one cannot easily update rows in a table, it's better to append them. 

Anyway, it looks like someone has to write code in Rust in order to add another backend like ClickHouse and I am not sure about the performance, since it will utilize ClickHouse merge tree engine as a KV store.

What do you think ?

### Question2: Why do you use a KV storage format when Cozo datalog model is based on n-ary relations and tuples ?
Can you share a brief explanation on reading/transferring data from the KV store to the memory and how joins are implemented under the hood ? What could be the main disadvantage of reading rows directly from a columnar database like ClickHouse ?  

### Question3: What kind of in-memory data structures are you using for CozoDB ?
Query execution from RocksDB is approximately double the time it takes to run the same queries in memory. I cannot see a big difference here. 

Moreover execution time for the point query using ClickHouse is a lot faster than the in-memory CozoDB query execution. Would you consider of integrating a lightning-fast DataFrame library like Polars ?

Notice: To draw some conclusion on the efficiency of your in-memory data structures, one must measure also the allocated memory size.

### Summary
My main interest is the integration and analysis of very large databases, knowledge bases, graph databases with extremely complex schema.  A relational datalog system like CozoDB, is a very interesting approach. But I think it has to be combined with a really fast columnar database and/or in memory dataframe processing to maximize query performance and optimize disk storage, memory space and time to import data.

PS: I have also opened a Hacker News discussion, [Fast Analytics and Graph Traversals with Datalog](https://news.ycombinator.com/item?id=37391333), hope you find it interesting.

**Comment by Slach** [comment]
maybe https://github.com/chdb-io/ could help for this kind of integration

**Comment by ben-pr-p** [comment]
I don't believe that either Clickhouse or Polars has proper transaction support, which I believe is a deal breaker for this (versus Sled, RocksDB, and SQLite, which do).

Secondly, I don't think this would be faster than any of the current storage engines. Cozo does a lot of recursive iteration through single point reads - this type of thing is substantially slower in an OLAP style engine like Clickhouse than RocksDB, which is optimized for ultra low latency / high throughput single point reads.

**Comment by infogulch** [comment]
A query engine that supports Apache Arrow data format would be ideal for querying and could unlock high storage compression. In particular, with Arrow cozo could *completely eliminate the serialization/deserialization overhead* when shipping data between language runtimes; we could be talking thousands of allocations and field ser/de per query. Not to mention that that query engines like Polars run extremely fast on Arrow.

I've considered proposing that cozodb use Arrow format for a while, but ben's is correct here: cozodb absolutely needs support for write transactions, and I'm not aware of an Arrow-enabled query engine that supports transactions, so I've held off making this proposal.

Columnar storage engines and formats in general show that there is a huge untapped performance potential waiting for transactional databases that adopt it, but until we get a columnar engine that can do transactions (and addresses the myriad of yet unsolved problems that such a fusion presents) we're stuck waiting.

**Comment by ben-pr-p** [comment]
@infogulch DuckDB supports transactions, is columnar, and I believe supports some zero copy arrow operations (at least with Python). 

Am I wrong that the important performance component for Cozo, though, is single point reads? Does Cozo’s query engine want what arrow affords?

**Comment by infogulch** [comment]
DuckDB seems interesting. I doubt cozo would want to use a SQL-based interface, but maybe it exposes a C api.

Currently cozo serializes the result of every query into json and deserializes it in the target language (for every language except rust). That's a lot of overhead that could be eliminated with Arrow. Also many high-bandwidth algorithms like pagerank could see performance improvements with a vector query engine.

But yes, whether these things would actually matter to Cozo is its own question.

**Comment by athanhat** [comment]
@infogulch about transactions, isn't it possible to separate concerns in a similar fashion like SingleStore DBMS that uses both a columnar engine for analytics and a row engine for transactions ?
@ben-pr-p those specific columnar engines, ClickHouse and Polars(Arrow Based) have no problem at all handling point queries, especially in reading mode (see my benchmarks above).

**Comment by ben-pr-p** [comment]
@athanhat I know it feels fast, but your results for point queries are very slow compared to the current engines. 

.01 second (10ms) or .04 second (40ms) is very slow for a single point read. I don’t know Rocks off the top of my head, but I know SQLite can get 1-2ms and I imagine Rocks beats it. 

I think there must be something wrong with the Cozo in memory benchmark there, or at least you’re comparing Cozo as a whole system to just the storage layer

**Comment by athanhat** [comment]
@ben-pr-p, I recognize that you do have a point here, because I am comparing the performance of CozoDB not inside Rust, but inside Python where there is delay due to the protocol used to transfer and display data.

**Comment by infogulch** [comment]
Thanks for correcting me on the fact that cozodb does not use json-based transfer for the python implementation, I'll have to investigate the code more carefully. I admit that the json encoding would not affect query performance for the queries and performance numbers we're discussing here.

<details>
<summary>
Because it was missing from your analysis I created a bulk import script. Click to expand this section and see it:
</summary>

```python3
from pycozo.client import Client
import pandas as pd
from itertools import islice

client = Client('rocksdb', "watdiv.db")
q = ":create WD {subject: String, predicate: String, object: String}"
client.run(q)

def batched(iterable, n):
    # batched('ABCDEFG', 3) --> ABC DEF G
    if n < 1:
        raise ValueError('n must be at least one')
    it = iter(iterable)
    while batch := tuple(islice(it, n)):
        yield batch

def records():
    with open('watdiv.10M.nt') as f:
        i = 0
        for line in f:
            parts = line.split("\t")
            parts[2] = parts[2].strip(" .\n")
            yield parts

total = 0
for batch in batched(records(), 100000):
    client.import_relations({'WD': {'headers': ['subject','predicate','object'], 'rows': batch}})
    total += len(batch)
    print(total, end='\r')
```

</details>

This script loads the 10,916,457 rows in ~90s on my machine with both rocksdb and sqlite.

Running this script to look up one row takes 9s with rocksdb and 20s with sqlite:

```python3
from pycozo.client import Client
import pandas as pd
client = Client('sqlite', "watdiv.sqlite")
q = "?[subject, predicate, object] := *WD[subject, predicate, object], subject='<http://db.uwaterloo.ca/~galuc/wsdbm/Product8622>', predicate='<http://purl.org/ontology/mo/opus>', object='\"908\"'"
print(client.run(q))
```

This is very surprising to me considering that if `=>` is unspecified then all fields are considered part of the primary key, and looking up a single value by key in an indexed data structure should require `O(log(n))` disk block reads which I would expect to resolve in microseconds at this scale; even 14ms looks ghastly slow, though it's neat that it can do it that fast while reading the whole file.

I have to point out that storing rdf data as a flat relation with string fields is less than ideal. Preferably subjects and predicates would be in a single relation indexed by some compact id and the triple data would reference that id instead of embedding the full name as a string. That said I don't think this affects the performance conclusion, even a naive implementation that dumps rdf data into string fields should be able to look up individual records much faster than this.

**Comment by athanhat** [comment]
@infogulch let's take for simplicity the same set, notice that URIs have bee stripped, this time an extra column `row` number is added and the relation is created with that column as a key.
```python
:create WD {row: Int => ent: String, attr:String, val:String}
```

Importing data from that `tsv` file in my machine takes 1min 8sec

---
Result from the following point query is returned in 7.67sec (clickhouse 0.014sec)
```python
?[row, user, attr, val] := *WD[row, user, attr, val], 
                                     user='User21846', 
                                     attr='email', 
                                     val='asserted unfailing whiskeys annulled idealistic'
```

---
Now, let's try to fetch the same row with the row key.
```python
"?[row, user, attr, val] := *WD[row, user, attr, val], row=10000000"
```
![image](https://github.com/cozodb/cozo/assets/13996696/a16c7612-4eae-4dad-9e64-cdbdd372f14a)

**Comment by infogulch** [comment]
That's not a helpful decomposition. The gold standard for triple storage and compression (which is very helpful for large graphs) in my opinion is TerminusDB which uses succinct data structures, which is a whole other can of worms. ([whitepaper](https://assets.terminusdb.com/research/succinct-data-structures-and-delta-encoding.pdf), [blog](https://terminusdb.com/blog/category/technical/))

But as I said, none of this is relevant until we get a better answer on *why* the point query is so slow. *The answer will have to come from someone profiling or analyzing cozodb, not by presenting more benchmark results.*

Just to prove that relational databases *can* be fast, I naively loaded all the records into sqlite3 and with `time` it returns the row in 0.005s with a primary key over all 3 columns.

<details>
<summary>
I ran these commands:
</summary>

```
qsv fmt -d '\t' -t ',' watdiv.10M.nt | qsv replace -s 3 ' \.$' '' > watdiv.10M.csv

sqlite3 wd.sqlite
> CREATE VIRTUAL TABLE temp.wdt USING csv(filename='watdiv.10M.csv');
> CREATE TABLE wd(subject, predicate, object, PRIMARY KEY(subject,predicate,object));
> INSERT INTO wd SELECT  * FROM wdt;

time sqlite3 wd.sqlite "select * from wd where subject = '<http://db.uwaterloo.ca/~galuc/wsdbm/Product8622>' and predicate = '<http://purl.org/ontology/mo/opus>' and object = '908';"
<http://db.uwaterloo.ca/~galuc/wsdbm/Product8622>|<http://purl.org/ontology/mo/opus>|908
```

I recognize that this is different from searching by scanning the entire file, but my point remains that relational databases *can* be fast. (It's likely much less than 1ms of query time, at this scale the time is dominated by shell and process startup.)

</details>

**Comment by zh217** [comment]
I did some tests myself, and, well, I agree that RocksDB cannot really compete with columnar store in terms of speed. These tests are very informative. And the "query planner" of CozoDB in its current state leaves a lot to be desired.

However, I'd say it is pretty difficult and not very productive to shoe-horn a columnar store as a CozoDB storage engine as it stands now. As a database written when one is not too experienced, a lot of original architectural decisions now get into the way. A rethinking of quite a lot of the key logics are required. Also, it seems that nobody has mentioned velox https://github.com/facebookincubator/velox, which I find quite interesting.

**Comment by athanhat** [comment]
@zh217 thank you for sharing CozoDB with the rest of us. I believe there are very few engineers that can go in such a depth to construct a DBMS, especially one that is close to a truly relational DBMS with Datalog query language. Kudos for the excellent initiative and the current implementation of a productive DBMS. For historical context, my attraction to Datalog stemmed from Clojure's triple-based DBMS but for several reasons I was looking for a **productive one** with n-ary relations until I found CozoDB.
Speaking about columnar layout engines, you mentioned Velox in C++ (Arrow-compatible) what advantage does this approach have in comparison to Polars (also Arrow compatible) in Rust ?
Finally you mentioned about rethinking of the key logic in CozoDB. Would you rewrite the Datalog query language based on a columnar storage/processing engine ? If yes, I will be interested in participating and learn more about Datalog implementation.
