### ISSUE TITLE
Will there be support for collation ?

### ISSUE THREAD

**Issue by Mr-Dispatch** [cozodb/cozo#178]
(searched whole repo for some mention, none found)
Some use-cases require sorting by "regional standards", and creating(!!maintaining!!) your own "index/sort" fields ain't fun :-/

**Comment by zh217** [comment]
Collation would be very nice, but we are not sure how best to implement it yet. Currently there is one and only one way to sort everything in CozoDB, and introducing collation would break that simplifying assumption and introduce lots of indirections. If there are examples of how other databases did it elegantly, suggestions are welcom.
