### ISSUE TITLE
Compile cozo crate if `libsqlite3-sys` is in dependency graph

### ISSUE THREAD

**Issue by a-0-dev** [cozodb/cozo#189]
I would like to use CozoDB, however I need another crate which indirectly depends on `rusqlite` and therefore `libsqlite3-sys`.

The way I understand the issue is, that since both `libsqlite3-sys` and `sqlite3-src` (the latter being a dependency of cozo) link to the native sqlite library, cargo will not compile both into the same binary.

Is there a recommended way to fix this? `rusqlite` seems to be quite popular, so I guess there needs to be a way to use cozo even if other dependencies use `rusqlite` (?)

**Comment by zh217** [comment]
Thanks for reporting this. In the next version there will be a feature flag to use `libsqlite3-sys` instead, which I think will fix this problem.
