### ISSUE TITLE
Feature request: Add FoundationDB backend

### ISSUE THREAD

**Issue by creatorrr** [cozodb/cozo#197]
I believe [FoundationDB](https://github.com/apple/foundationdb) could be an excellent backend for cozo. It's highly performant, distributed and transactional key-value store. Thoughts @zh217 ?

**Comment by docteurklein** [comment]
I also considered fdb when discussing tikv support in #2. It's for sure a good idea, but would suffer the same perf limitations due to remote storage.

**Comment by creatorrr** [comment]
makes sense

**Comment by creatorrr** [comment]
closing this for now
