### ISSUE TITLE
Future plans and sponsorship?

### ISSUE THREAD

**Issue by creatorrr** [cozodb/cozo#198]
Hey @zh217 ,

Our startup is now heavily using cozo and we love it! I wanted to know your plans on the future of cozo and whether you are seeking sponsorship. I am not sure how much we could contribute or how you might think about this but I am sure the community would love to support this project! :)

**Comment by gisborne** [comment]
I’m sure the community would love to hear more about what you’re doing.

**Comment by zh217** [comment]
@creatorrr, I'm glad that you find CozoDB valuable! Currently, we do not have any sponsorship, and CozoDB generates no income for anyone. However, as a startup, we use CozoDB internally, so the future of CozoDB is not in question.

I understand that our internal needs for CozoDB may not always align with our users'. Sometimes, there is a conflict of priorities. For example, in recent months, we have been busy with LLM stuff, and the database part of our project is currently considered "good enough." As CozoDB is open source, if you have any urgent feature requests or bugs that need to be fixed, please feel free to ask here. We, along with the community, will try our best to accommodate these requests when we have spare resources. Currently, contributing to CozoDB requires signing a CLA, but this requirement will soon be removed. The CLA was put in place when we did not have a clear understanding of the license CozoDB uses, so we wanted the flexibility to change the license easily if needed. However, we have now decided that the current license is fine. Once the CLA requirement is removed, individuals and companies will likely have fewer reservations about making significant code contributions to the project.

As for even stronger guarantees about future features and maintenance, we are not too sure yet. Currently, we do not have a business model for the project and have not thought about generating income from it. We are open to any suggestions in this regard.

**Comment by tausifcreates** [comment]
@zh217 I have some thoughts that you may consider -

1. A Neo4j like business model where some advanced features to be behind paywall and a free to use community version.

2. Sponsorships are not a stable medium of income. People can start/pause sponsoring at  their own will, and generally that amount is likely to be small, unless one or two big players in the industry start sponsoring.

3. Some big players may have the resources to sponsor Cozodb but not directly monetizing from it, like Microsoft does to vscode, as vscode works as an entry point to MS proprietary extensions and profitable Copilot.

4. Neo4j has a managed cloud offering called 'Aura DB', which is quite booming.

**Comment by creatorrr** [comment]
We are a startup as well so I completely understand, @zh217 . :)

Some ideas:
1. A short public roadmap and list of priorities that align with you would be great.
2. A bug/feature bounty thing maybe? For instance, we aren't a rust shop so contributing to `cozo-core` would require picking it up but we'd be happy to sponsor other rust devs to work on PRs.
3. Some sort of long-term plan for involving more people from the community and maybe evolving cozo into an independent project?

**Comment by creatorrr** [comment]
@zh217 closing this for now.
