### ISSUE TITLE
Build fails on Linux.

### ISSUE THREAD

**Issue by LexCutch** [cozodb/cozo#205]
In ``cozorocks/src/brdige/mod.rs``
``pub enum StatusCode``
``pub enum StatusSubCode``
have 17 elements, doesn't fit into uint8.

It fails the build. I haven't looked deeper. 
Seeing the last status code ``kMaxCode`` ``kMaxSubCode`` not used anywhere in the code - I commented them out.

Build passes.

Maybe a better fix is just a couple of lines below: changing a uint8 to uint16, but as I said, I didn't look.
p.s. ran cargo test - no red in my terminal.

**Comment by LexCutch** [comment]
Well, please ignore my ignorance.
uint8 is not limited by 16 elements.
My bad. 

It seems like just setting them to ``=16`` settles the case.
Somehow the bridge expects them to be ``==16`` in the c-code it generates.
And them not having been set to any value, gives rustc the freedom to set em freely.

**Comment by RainerStorm** [comment]
I found that the actual problem lies in a misalignment to Rocks; StatusSubCode contains         kMergeOperandThresholdExceeded = 16. Adding this solved the problem for me.

**Comment by zh217** [comment]
This is due to using a newer version of RocksDB source than CozoDB expects. The next release will update to the latest version of RocksDB. Thanks for the report.
