### ISSUE TITLE
Comparison with Surrealdb

### ISSUE THREAD

**Issue by ansarizafar** [cozodb/cozo#21]
Cozo and SurrealDB https://surrealdb.com/ are two new and innovative databases and both DBs can learn from each other. I don't want to use decades old relational databases for a new project so I am looking for a high level or If possible detailed comparison between Cozo and SurrealDB.

**Comment by zh217** [comment]
Thanks for your interest but we won't do it. What we will do is to document what Cozo does in more details in future versions of the docs. As developers of Cozo we naturally know Cozo much better than SurrealDB, so any comparisons and judgements we make are naturally biased and ultimately worse than useless for end users.
