### ISSUE TITLE
Possible bug in `:rm` operation

### ISSUE THREAD

**Issue by aramallo** [cozodb/cozo#220]
I have an issue with the `:rm` syntax. I consider this a bug, but maybe this was a design decision?

Asumming I have a stored relationship called `graph` defined as:

```
:create graph { subject: string, predicate: string, object: any, name: string => }
```

The following script works to remove a row:

```
?[subject, predicate, object, name] <- ['a', 'b', 100, 'g1']
:rm graph { subject, predicate, object, name }
```

But the following two alternatives will not work

Alt 1: 
```
:rm graph { subject: 'a', predicate: 'b', object: 100, name: 'g1}
```
Returns ` "The query parser has encountered unexpected input / end of input at 21..21"`

```
:rm graph { 'a', 'b',  100, 'g1'}
```

Returns `"The query parser has encountered unexpected input / end of input at 12..12"`

Is this a bug, or `:rm` was designed to only work with variable bindings?

**Comment by Volland** [comment]
you need a ?[] part to be present in rm . only create allow form without query statement

**Comment by Volland** [comment]
it is a part of documented bechavior

**Comment by aramallo** [comment]
Thanks @Volland !!!
