### ISSUE TITLE
Feature request: be able to build queries directly in rust, bypassing the script parser

### ISSUE THREAD

**Issue by skyrod-vactai** [cozodb/cozo#224]
What I wanted to do was be able to write cozo queries directly in rust, and use the various rust structs in the cozo lib to bypass the cozoscript parser. Then I wouldn't have to mess with formatting strings, and it would potentially be a lot cleaner. 

However all those structs are all crate private, so I can't bypass the parser. I'm talking about `InputProgram` and the various other structs contained therein - I'd like to be able to instantiate those myself, and pass them to whatever function executes the parsed script.

**Comment by andrewbaxter** [comment]
I'm not sure if this is a bad idea, but I'd like to do some security filtering on user queries:
- Restricting queried relations
- Adding membership clauses to relationship atoms

AFAICT recursing the datalog and making changes should be pretty simple and comprehensive, if it's basically a typed tree of enums/structs.

I'd be happy with something explicitly unstable.

**Comment by andrewbaxter** [comment]
I made a PR, let's see how this goes...
