### ISSUE TITLE
bug: `ReorderSort` does not work as expected

### ISSUE THREAD

**Issue by creatorrr** [cozodb/cozo#274]
`ReorderSort` does not return anything. Am I doing something wrong? @zh217 

Query:
```
test[a] <- [[1], [2], [3]]

?[i, x] <~ ReorderSort(test[a], out: [a], sort_by: [-a])
```

Expected:
| i  | x  |
|---|---|
| 1  | 3  |
| 2  | 2  |
| 3  | 1  |

Actual:
| i  | x  |
|---|---|

**Comment by wti** [comment]
See <https://github.com/cozodb/cozo/blob/6ab063c627a57242ff42d563dfa1ce41264bcc72/cozo-core/src/fixed_rule/utilities/reorder_sort.rs#L112>:

could be 
```
if 0 != count && count > take_plus_skip {
    break;
}
```

**Comment by wti** [comment]
Proposed fix in PR https://github.com/cozodb/cozo/pull/277

**Comment by creatorrr** [comment]
Ah that makes sense! Thanks for the catch and the fix 😄 Closing
