### ISSUE TITLE
panic when using empty constant

### ISSUE THREAD

**Issue by docteurklein** [cozodb/cozo#3]
Just trying things out, I noticed this panic: 
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/query/stored.rs:380:25
[2022-11-08T12:48:51Z ERROR cozoserver] 2022-11-08 12:48:51.798700 Handler panicked: POST /text-query 366.062µs
```
when handling this query
```
{
?[id, name] <- [[]]
:replace product {id: Int, name: String}
}
```

Which is a stupid query, I know, but I struggle to create an empty stored relation without having an output relation (`?`), even though the docs say the contrary:
```
{
:replace product {id: Int, name: String}
}
```
says:
```
parser::no_entry

  × Program has no entry
  help: You need to have one rule named '?'
```

EDIT: It seems related to the usage of `:replace` instead of `:create`.

**Comment by zh217** [comment]
Thank you for the report! This will be fixed in the next release!
