### ISSUE TITLE
suggestion: don't unify variables named _ (underscore) in rule body

### ISSUE THREAD

**Issue by ear7h** [cozodb/cozo#30]
Hello, I'd like to suggest not unifying instances of `_` variables. That is, treat each instance of `_` as separate.
```
r1[] <- [[1, 'a'], [2, 'b']]
r2[] <- [[2, 'B'], [3, 'C']]

?[l1, l2] := r1[_ , l1], r2[_ , l2]
# actual behavior
# ?[l1, l2] := r1[a , l1], r2[a , l2]
# expected behavior
# ?[l1, l2] := r1[a, l1], r2[b, l2]
```

Some prior art, `rego` of Open Policy Agent behaves this way: https://play.openpolicyagent.org/p/5qfwdxgG5k

**Comment by zh217** [comment]
Good idea, I actually wanted it to be this way as well, but was lazy to implement it.

Perhaps it will be in the next version.

**Comment by ear7h** [comment]
That was fast! Thank you!
