### ISSUE TITLE
ownership issue in backup_db in the Rust API

### ISSUE THREAD

**Issue by BrianHicks** [cozodb/cozo#32]
Hey there! Thanks for a very promising database!

I'm writing an ingestor and found myself wanting to use the `backup_db` method on `Db<Storage>`. This was harder than I expected, however, because that method needs to take an owned string as a path. This means I can't use the `PathBuf` I already have—instead, I have to convert that to a string (which is not always safe, because paths can have invalid unicode) and allocate a new string, since the method requires ownership.

Would it be possible to change this to be a borrowed `std::path::Path` instead? Or, if it *has* to be owned, a `PathBuf`?

**Comment by zh217** [comment]
Sure, will iron this out in the next release. The main reason was that the path needs to be passed to the C++ world in the case of RocksDB engine, and I am still a bit confused how to safely do this across all platforms (I believe passing the underlying bytes is OK, but not too sure).

**Comment by zh217** [comment]
The API in v0.5 doesn't take strings anymore.
