### ISSUE TITLE
Tutorial/doc: improve example

### ISSUE THREAD

**Issue by redbar0n** [cozodb/cozo#37]
Suggestion for improving the recursive example from the tutorial, so it's slightly more intuitive.

Current:

```cljs
parent[] <- [['joseph', 'jakob'], 
             ['jakob', 'issac'], 
             ['issac', 'abraham']]
grandparent[gcld, gp] := parent[gcld, p], parent[p, gp]
?[who] := grandparent[who, 'abraham']  # => 'jakob'
```

Issues:

- The grandparent function is interpreted as: "who is the grandparent of X?" or "find the grandparent of X", but currently Jakob comes out as the grandparent of Abraham, when it's really the other way around.
- What does gcld mean? It wasn't documented and I didn't understand it.
- Parent child relationship is more natural to describe top-down/left-right than bottom-up/right-left. Especially since the "array" is called parent, so the focus is on the parent (i.e. top-down).
- Typo: issac → isaac
- Typo: "classical example recursive example" → "classical recursive example"
- It'd be nice if the example showed one more level of recursion, i.e. great-grandparent.

Suggestion:

```
parent[] <- [['abraham', 'isaac'], 
             ['isaac', 'jakob'], 
             ['jakob', 'joseph']]

grandparent[A, C] := parent[A, B], parent[B, C]

great_grandparent[A, D] := parent[A, B], parent[B, C], parent[C, D]

?[who] := great_grandparent[who, 'joseph']  # => 'abraham'
```

which is also more in line with [the example from "A Guided Tour of Relational Databases and Beyond", by Mark Levene & George Loizou](https://books.google.no/books?id=9CARBwAAQBAJ&pg=PA24&lpg=PA24&dq=%22datalog%22+grandparent%5Bwho,+%27abraham%27%5D&source=bl&ots=lahiEe6Y21&sig=ACfU3U0N3eHRP2lNFTMEK8-R_-w7zQbvfg&hl=en&sa=X&ved=2ahUKEwjInYPPoPD8AhXDVfEDHRw5BngQ6AF6BAgJEAM#v=onepage&q=%22datalog%22%20grandparent%5Bwho%2C%20'abraham'%5D&f=false) and [the other example](https://dev.to/rabraham/introduction-to-datalog-bashlog-in-python-1a38) I found when googling for it (since you mentioned it was a classical example).

**Comment by cwarden** [comment]
> What does gcld mean? It wasn't documented and I didn't understand it.

Clarifying this addresses the issue.  `gcld` is grandchild (`p` is parent; `gp` is grandparent).  Therefore, the example is "who is the grandchild of abraham?

**Comment by redbar0n** [comment]
Ok, I see. Then the function should maybe be called `grandchild` not `grandparent` since that's what it's finding. Maybe `parent[]` should be called `child[]` also then.

**Comment by cwarden** [comment]
Perhaps two queries in the example would be beneficial those new to datalog to illustrate that it's querying a relation rather than calling a function.

```
?[who] := grandparent[who, 'abraham']  # => 'jakob'
?[who] := grandparent['jakob', who] # => 'abraham'
```

(I'm not affiliated with the project, or even a user yet.  Just trying to help too.)

**Comment by zh217** [comment]
Nice points, I will update the docs later.
