### ISSUE TITLE
Replace Rocksdb with Speedb

### ISSUE THREAD

**Issue by ansarizafar** [cozodb/cozo#40]
Speedb is 100% compatible with Rocksdb. The performce/efficiency difference between Rocksdb and Speedb is quite big and Speedb also solves some of Rocksdb issues.
It is worth the effort to replace Rocksdb with Speedb.

https://www.youtube.com/watch?v=CMpB8AyHwvI&feature=youtu.be
https://www.speedb.dev/

**Comment by zh217** [comment]
There are currently no plan to officially support more storage engines. With the current API available, adopting code for one of the existing storage engines for new one isn't hard if you really need it.
