### ISSUE TITLE
how can i define my own method or import some other famous function

### ISSUE THREAD

**Issue by a1032077316** [cozodb/cozo#46]
how can i define my own method or import some other famous function

**Comment by zh217** [comment]
It depends on from what language/environment you are driving Cozo, here are some examples:

* [Python](https://github.com/cozodb/pycozo#user-defined-fixed-rules)
* [Rust](https://docs.rs/cozo/latest/cozo/enum.DbInstance.html#method.register_fixed_rule)
* [HTTP](https://github.com/cozodb/cozo/tree/main/cozo-bin#api)
* [NodeJS](https://github.com/cozodb/cozo/blob/main/cozo-lib-nodejs/example.js#L26-L29)

Not all client wrappers currently have this functionality exposed, but you can look at the source of those above to see how it can be added.
