### ISSUE TITLE
:replace doesn't seem to work on ephemeral relations after explicit creation

### ISSUE THREAD

**Issue by jam10o-new** [cozodb/cozo#49]
I was incredibly confused when making transactions that created (either explicitly or via :replace itself,) an ephemeral relation and then later tried to replace them, because I would always see:

  × when executing against relation '_test'
  ╰─▶ Cannot destroy temp relation
  
Here's a minimal reproduction:
```
{?[a] <- [[1], [2], [3]]; :replace _test {a}}
{?[a] <- [[1]]; :replace _test {a}}
```
 Hoping this is not intended behavior! It makes a lot of things significantly more convoluted to implement!

**Comment by zh217** [comment]
You are right, this shouldn't be forbidden. Will fix in the next release.
