### ISSUE TITLE
Document limitations / impact of large values

### ISSUE THREAD

**Issue by FeldrinH** [cozodb/cozo#54]
Cozo supports storing strings and byte arrays. These at least in theory allow you to store a very large amount of data in a single row. This naturally raises the question of how much data can/should you store in a single row in practice.

It would be useful to have the documentation provide clear answers to the following questions:
* Is there a limit to the amount of data you can store in a single value or single row?
* Are there performance impacts or other special considerations for working with large values such as long strings or large byte arrays?

**Comment by zh217** [comment]
It is available in the online documentation at https://docs.cozodb.org/en/latest/stored.html#storing-large-values
