### ISSUE TITLE
REPL's `%set` command should parse values using CozoScript syntax

### ISSUE THREAD

**Issue by rmgaray** [cozodb/cozo#55]
I was trying to set some parameters in the REPL, but I could not understand why I was getting an error:

```
=> %set flag true

 × expected value at line 1 column 1
```

After reading how the parsing of parameters is done in the REPL, I noticed that it just uses `serde_json::fromStr` to parse a `DataValue` ([Link](https://github.com/cozodb/cozo/blob/5a64821eca0a39920b8b0f88024e53801f26a1f8/cozo-bin/src/repl.rs#L211)) . So the way to do what I wanted is this:

```
=> %set flag {"Bool": true}
=> %params
{
  "flag": {
    "Bool": true
  }
}
```

This does not look right, I assume the intention here was to parse the value as it is usually done in a standard script.

**Comment by zh217** [comment]
This is a bug, will fix it.
