### ISSUE TITLE
Convert values in list to relation

### ISSUE THREAD

**Issue by hetzge** [cozodb/cozo#62]
Hello I am new to cozo and datalog.

How do i convert the values of a list to a relation ?

Example:
```
input[values] <- [[1, 2, 3]]
?[value] := ???
```

Expected result:
```
value
1
2
3
```

**Comment by zh217** [comment]
Your original `input` relation defines a relation of three fields, not one.
I think you really meant:
```
input[values] <- [[1], [2], [3]]
?[value] := input[value]
```

More simply:
```
?[value] <- [[1], [2], [3]]
```

This is fine as well:
```
?[value] := value in [1, 2, 3]
```

If you really want to use your original `input` relation with three fields:
```
input[a, b, c] <- [[1, 2, 3]]
?[value] := input[a,b,c], value = a or value = b or value = c
```

**Comment by hetzge** [comment]
Thank you very much. 

You are right. My example was wrong. My goal was to prevent something like this [[1], [2], [3]] because it is hard to type and read if you have many values.
What i missed was the "in" operator.
Now this is my solution:
```
input[values] <- [[[1, 2, 3]]]
?[value] := input[values], value in values
```
