### ISSUE TITLE
Better explain Validity

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#67]
The docs are generally great, but  I find the discussion of validity confusing. The crucial part says:

> All rows with identical key parts except the last validity part form the history for that key, interpreted in the following way: the fact represented by a row is valid if its flag is true, and the range of its validity is from its timestamp (inclusive) up until the timestamp of the next row under the same key (excluding the last validity part, and here time is interpreted to flow forward). A row with a false assertive flag does nothing other than making the previous fact invalid.

I am confused about what the Boolean does.

"the range of its validity is from its timestamp (inclusive) up until the timestamp of the next row" says the timestamp part behaves in the obvious way: a row is considered true between its timestamp and the timestamp of the next row with the same key, sorted by timestamp. Fine.

But:

" A row with a false assertive flag does nothing other than making the previous fact invalid" this *sounds* like the regular timestamp behaviour. When I insert a row with the same key but a later timestamp, the previous row could be called invalid as it's false after the new timestamp.

There is further explanation, but I don't understand it at all:

> It is possible for two rows to have identical non-validity key parts and identical timestamps, but differ in their assertive flags. In this case when queried against the exact timestamp, the row is valid, as if the row with the false flag does not exist. The use case for this behaviour is to assert a fact only until a future time when that fact is sure to remain valid. When that time comes, a new fact can be asserted, and if the old fact remains valid there is no need to :rm the previous retraction.

**Comment by zh217** [comment]
Yes, these are not very clear, I will add some examples to the docs when I find the time.

**Comment by zh217** [comment]
The new docs gave some examples.
