### ISSUE TITLE
Share benchmark code

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#72]
The benchmarks are very interesting reading.

It would be useful both in understanding the benchmarks but also in seeing examples of using the Rust API.

Please share the source of the benchmarks.

Sorry if you’ve already shared them, but I looked through the benchmark piece again and I didn’t see it. If it’s there, maybe make it more obvious?

**Comment by zh217** [comment]
It's here: https://github.com/cozodb/cozo/blob/main/cozo-core/benches/pokec.rs

It is not polished at all. Also you will need to get the data from memgraph's perf repo.
