### ISSUE TITLE
Support Lazy Columns

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#73]
Lazy Columns are not traditionally nullable, but a row can be created without a value for such a column, and it can be then set later, but only once. I expect these can be made more efficient than traditional null fields, as once rows are fully ground, null checks and flags are no longer required.

This is a natural way to express a distributed function call: https://frest.substack.com/p/distributed-relational

**Comment by zh217** [comment]
Lazy columns won't be more efficient. Currently typing is only used to check the consistency of data, and in the storage layer everything is dynamically typed (rather like Python's typing).

I'm not sure what kind of problems this is going to solve? I think as long as users can observe null values, then the column should be nullable.

**Comment by gisborne** [comment]
If you've a table where some columns are nullable, you have to do extra work to track which columns are null or not eg Postgres uses a bitmap.

If you know that all the columns are ground and won't ever be null, you don't need to do that any more for that row, saving a little work.

But it's more about the data model. Null is somewhat problematic in databases (hopefully we use a more principled three-valued logic than SQL does!), but this is something that is I think not problematic. And if you read my piece, I think there is an under-appreciated and important use case.

OTOH, even if this is desirable, it's not terribly important. Just wanted to mention the idea in case you liked it.
