### ISSUE TITLE
Maybe relations as values?

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#74]
It would be nicely orthogonal if, rather than living in a single global namespace, relations could be field values. Now I can organise my relations however suits.

The same idea might apply to other things — theories (collections of rules, values and so on)…

**Comment by zh217** [comment]
On the other hand this makes reasoning about the database structure much more difficult. A priority nowadays is to let not-too-bright AI be able to use the database. So unless there is an exceedingly strong use case for this, it won't be included.

**Comment by gisborne** [comment]
A typical medium+ size company's databases will have thousands of relations in its major databases. Managing that is challenging. It mostly works because only dbas need to know the larger picture and its structure changes only gradually. No GUI I've ever seen makes managing that number of tables reasonable, also.

I think we can do better. I have been working on a model with relations and namespaces. The top-level thing was a namespace and one of the value types supported is relation. You could have relations and namespaces as column types or namespace values.

This leaves the management of the relations and everything else up to the designer of the application.

I don't see an equally satisfying solution, particularly in regard to orthogonality.

I intend to build a layer like this on top of Cozo if Cozo doesn't, but it would be better as a standard feature.

**Comment by gisborne** [comment]
A relation value is also a natural way to represent a foreign key.

**Comment by gisborne** [comment]
How about a function that turns a relation name into a reference to the relation?

**Comment by matthiasautrata** [comment]
> I think we can do better. I have been working on a model with
relations and namespaces. The top-level thing was a namespace and one
of the value types supported is relation. You could have relations and
namespaces as column types or namespace values.

I realize that this is a long learning curve. But it might make sense
to take some inspiration from 

https://www.w3.org/TR/rdf11-concepts/

https://www.w3.org/TR/rdf-schema/

https://www.w3.org/2021/12/rdf-star.html

https://www.w3.org/TR/owl2-primer/

https://www.w3.org/TR/shacl/

Describes model, namespaces, rules, constraints and a few extra
things. You know what they say: "If you copy once, it is called
plagiarism, if you copy all the time, it is called research."

I am not at all suggesting that the W3C already solved all problems.
But at least they have been thinking about web-scale models for some
time and it is intriguing to think about "composable models" (my term
and I am not sure that it is ideal. Somewhere in the back of my head
it looks like data-models being plugged together from smaller modular
ones. Seems eerily similar to using libraries in programming
languages.)

---

Matthias Autrata +1-201-305-0042

**Comment by gisborne** [comment]
Thanks for the advice.

I’m passing familiar with such things. I worked at Cycorp for a couple of years, if that means anything to you.
