### ISSUE TITLE
Can I not :put literal values?

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#84]
```
:create test {name: String}

:put test {['Cozo']}
```
```
  × The query parser has encountered unexpected input / end of input at 40..40
   ╭─[2:1]
 2 │ 
 3 │ :put test {['Cozo']}
```

An EBNF might be part of the answer here, but I have semantic confusions also.

**Comment by gisborne** [comment]
```
:create test {name: String}
?a <- [['Cozo']]
:put test {name => a}

  × The query parser has encountered unexpected input / end of input at 28..28
   ╭─[1:1]
 1 │ :create test {name: String}
 2 │ ?a <- [['Cozo']]
   · ▲
 3 │ :put test {name => a}
```

I am confused about the larger syntax/semantics here.

**Comment by gisborne** [comment]
This is also confusing:

```
:create test {name: String}

?[a] <- [['Cozo']]

:put test {a}
```

query::relation_not_found

  × Cannot find requested stored relation 'test'

**Comment by atlewee** [comment]
It seems like you cant create and put in the same query/transaction.
If you first run the create and then the put as separate queries it will work.

Or you can run multiple queries at once by putting them in curlybrackets:
```
{
:create test {name: String}
}
{
?[name] <- [['Cozo']]
:put test {name}
}
```

If you want to keep the a as binding name:
```
:create test {name: String}

?[a] <- [['Cozo']]
:put test {name=a}
```

**Comment by gisborne** [comment]
Thanks for that.

I am still confused about a couple of things.

This works:

```
{
:create _test {name: String}
}
{
?[name] <- [['Cozo']]
:put _test {name}
}
```

So I guess an ephemeral relation is within a single script, not a single transaction? I guess.

But why does this not work?

```
{
:create _test {name: String}
}
{
:put _test {['Cozo']'}
}
```

I tried 'Cozo', ['Cozo'] and [['Cozo']] and none of those worked.

**Comment by zh217** [comment]
You can't, these letters in `:put` doesn't refer to a single value. It is working as expected.

**Comment by infogulch** [comment]
I don't understand the purpose of this restriction, it feels arbitrary. Why is binding to a variable required when there is only one possible value?

```
{
:create _test {name: String, kind: String}
}
{
:put _test {name: 'Cozo', kind: 'DB'}
}
# why can't this↑ be desugared to this↓ automatically?
{
?[name, kind] := name = 'Cozo', kind = 'DB'
:put _test {name, kind}
}
```

**Comment by zh217** [comment]
You can have a `?[]` together with a `:create` in the same query. In addition, there are some utilities in the python client that allows you to do simple mutations:

```python
db.put('rel_name', {'a': 1, 'b': 2})
db.put('rel_name', [{'a': 1, 'b': 2}, {'a':3, 'b': 4}])
```
