### ISSUE TITLE
which HNSW lib was used?

### ISSUE THREAD

**Issue by jianshu93** [cozodb/cozo#86]
Dear cozo team,
I found this hnsw library very fast and efficient: https://github.com/jean-pierreBoth/hnswlib-rs

I am not sure which one is used here but it seems this one is the most convenient in terms of parallelism.

Thanks,

Jianshu

**Comment by zh217** [comment]
We wrote our own. The library you mentioned keeps everything in memory and cannot do incremental writes to disk, which makes it unsuitable for this project.
