### ISSUE TITLE
FTS index creation error

### ISSUE THREAD

**Issue by chuanqisun** [cozodb/cozo#90]
There seems to be some issue when parsing the `filters` parameter. Repro vis wasm demo

```
:create table {k: String => v: String?}
```
```
::fts create table:index_name {
    extractor: v,
    extract_filter: !is_null(v),
    tokenizer: Simple,
    filters: [],
}
```

Error:
```
Filters must be a list of filters
```

![image](https://user-images.githubusercontent.com/1895289/236301330-b97c9c93-4f03-4bbf-886c-087d69957482.png)

**Comment by zh217** [comment]
This is strange. It works in my private build but fails in the public one.

For the moment, the only way to proceed with the public build is to omit the filters parameter.
