### ISSUE TITLE
syncing with eventual consistency

### ISSUE THREAD

**Issue by gisborne** [cozodb/cozo#96]
It would be fantastic to be able to set up multiple Cozo database to synchronise with each other, and have that built into the database.

I think the world would be likely to take notice of Cozo significantly more quickly if you could tell developers they can make an offline-capable mobile app that automatically syncs in the background.

I understand that there are some complexities involved. Ideally, I think there would be a simple base case that is just supported, and the developer can provide different parts of the behaviour — particularly conflict resolution — in the host language if the default behaviour doesn't suit.

eg I make a OneNote type personal information app. The default behaviour is likely to be just keeping the most recent version of something. Likely the documents or paragraphs or something involved are just blobs, and I can provide a merge function for these blobs if I want something more sophisticated.

**Comment by zh217** [comment]
There is no plan to support multi-node features. In fact such features would probably require more code to implement than the entire current codebase, which is certainly beyond what we can do with current resources..
