### ISSUE TITLE
Unexpected error in query parser

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#97]
Hi,

Consider the following program:
```
vckg[a, b] <- [["a", 0]]

karb[C, C] := vckg[C, D]
orqn[A, A, A] := vckg[A, B]

?[a, b, c] := orqn[a, b, c]
```
I run this program in https://www.cozodb.org/wasm-demo/ and got the error message:

```
parser::pest

  × The query parser has encountered unexpected input / end of input at 65..65
   ╭─[3:1]
 3 │ karb[C, C] := vckg[C, D]
 4 │ orqn[A, A, A] := vckg[A, B]
   ·               ▲
 5 │ 
   ╰────
```
But if I remove the first rule `karb[C, C] := vckg[C, D]`, then this program can run correctly, but there is not any relationship between the first rule and the second rule. Is this a bug or I do something wrong?

**Comment by zh217** [comment]
Thanks for the report, it's a bug.

Here's a even shorter one that doesn't work:

```
?[C] := C = 1
orx[C] := C = 1
```

And this one does:

```
?[C] := C = 1
x[C] := C = 1
```

So it is the parser trying to parse `or`. It will be fixed in the next release. Meanwhile a walkaround is to use a different rule name than `orqn`.

**Comment by DerZc** [comment]
Thank you for your response and fixing it!
