### ISSUE TITLE
Unexpected error `Encountered unsafe negation, or empty rule definition`

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#98]
Hi,

Consider the following program:
```
ywcc[a] <- [[1]]

noto[A] := ywcc[A]
?[A] := noto[A]
```
I run this program in https://www.cozodb.org/wasm-demo/ but get an error message:
```
eval::unsafe_negation

  × Encountered unsafe negation, or empty rule definition
   ╭─[3:1]
 3 │ noto[A] := ywcc[A]
 4 │ ?[A] := noto[A]
   ·            ────
   ╰────
  help: Only rule applications that are partially bounded, or expressions / unifications that are completely bounded, can be safely negated. You may also encounter this error if your rule can
        never produce any rows.
```
But there is not any negation in this program and `noto` should not be empty.

**Comment by zh217** [comment]
It's the same problem as before: try not use the name 'noto' since the parser currently tries to parse it as `not o[A]`.

It's already fixed, but will only be available when the next version is released.

**Comment by DerZc** [comment]
Sorry for the duplicate report and thank you for your work!
